name = "FTAM Reloaded"
author = "Reforged Network"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c9af16ccbe3e18088e740477842469f971a9e348a6e2ea94dcbe8256aebc7120"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
