name = "FTAM Reloaded"
author = "Reforged Network"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb4aa03723d8ffbdbc8026f9aff24a7230c272f4adbf1a33381d1ed9f65f8d76"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
