name = "FTAM Reloaded"
author = "Reforged Network"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2feb63ade811dbf51895ac6a546875b37d90ebc5033cb01d2394a2777c0d458f"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
