name = "FTAM Reloaded"
author = "Reforged Network"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d4ac7244221695969e506277451f492a591d8fee8ecff51530c4c89a0718fca9"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
