on:
    workflow_dispatch:
permissions:
        contents: write
        pull-requests: write

jobs:
    update:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            # -------- SETUP --------

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: "1.24"

            - name: Install Packwiz
              run: |
                  go install github.com/packwiz/packwiz@latest

            # -------- Update --------   
                  
            - name: Run Packwiz Update
              working-directory: pack
              run: |
                   yes | packwiz update --all

            # -------- Commit -------- 
            - name: Commit changes
              env:
                  GITHUB_TOKEN: ${{ github.token }}
              run: |
                git config user.name "github-actions[bot]"
      
                git checkout -b automated/packwiz-update
      
                git add .
                git commit -m "chore: update packwiz mods"
      
                git push --force origin automated/packwiz-update

            # -------- Pull-Request -------- 
      
            - name: Create Pull Request
              env:
                  GITHUB_TOKEN: ${{ github.token }}            
              run: |
                gh pr create \
                  --title "Automated Packwiz Update" \
                  --body "This PR was automatically generated by GitHub Actions after running \`packwiz update --all\`." \
                  --base main \
                  --head automated/packwiz-update                   
